### ISSUE TITLE
get_song requests: 'dict' object is not callable

### ISSUE THREAD

**Issue by corrmaan** [gmusicproxy/gmusicproxy#125]
With any `get_song` request the following error is output by GMusicProxy ten times, with only the port number in the first line increasing by two with each repetition:

```
Listening on 0.0.0.0:9999...
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 40006)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python-exec/python3.8/GMusicProxy", line 570, in handle_one_request
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/lib/python-exec/python3.8/GMusicProxy", line 84, in do_GET
    self._process_request('GET', self.server.get_handlers)
  File "/usr/lib/python-exec/python3.8/GMusicProxy", line 176, in _process_request
    dispatch(self, params) or self._send_500(params)
  File "/usr/lib/python-exec/python3.8/GMusicProxy", line 87, in handle_song
    send_icy_meta = 'icy-metadata' in self.headers or params('icy-metadata', False)
TypeError: 'dict' object is not callable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 40008)
...
```

**Comment by corrmaan** [comment]
Sorry I'll reply with debug output tomorrow

**Comment by jdwoody** [comment]
I have this fixed. I will push a release this weekend.

**Comment by corrmaan** [comment]
Oh great, thanks. I wasn't sure if it was gmusicproxy or one of of it's dependencies. 

I suppose the 10x repetition is probably my browser retrying the request.

**Comment by jdwoody** [comment]
There's a retry mechanism on the server side. This was kind of strange as it didn't throw the error consistently and only happens on certain versions of python.

**Comment by jdwoody** [comment]
Give 2.2.0 a shot. Thanks for reporting.

**Comment by corrmaan** [comment]
That did it! Thanks for all of your hard work.
