### ISSUE TITLE
Error installing dependencies and starting

### ISSUE THREAD

**Issue by MarcelloTheArcane** [gmusicproxy/gmusicproxy#129]
Hello

I'm trying to update to the latest version (2.2.0).

I ran `git pull origin master` which updated the files successfully.

Now I'm trying to install the `requirements.txt`, but I get this error:

```
Traceback (most recent call last):                                              
  File "/usr/bin/GMusicProxy", line 4, in <module>                              
    __import__('pkg_resources').require('gmusicproxy==1.0.9b2')                 
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3095, 
in <module>                                                                     
    @_call_aside                                                                
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3079, 
in _call_aside                                                                  
    f(*args, **kwargs)                                                          
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3108, 
in _initialize_master_working_set                                               
    working_set = WorkingSet._build_master()                                    
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, i
n _build_master                                                                 
    return cls._build_from_requirements(__requires__)                           
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 585, i
n _build_from_requirements                                                      
    dists = ws.resolve(reqs, Environment())                                     
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, i
n resolve                                                                       
    raise DistributionNotFound(req, requirers)                                  
pkg_resources.DistributionNotFound: The 'gmusicproxy==1.0.9b2' distribution was 
not found and is required by the application                                    
[ec2-user@ip-172-31-12-48 gmusicproxy]$ pip install -r requirements.txt         
Obtaining file:///home/ec2-user/gmusicproxy (from -r requirements.txt (line 3)) 
Collecting gmusicapi==13.0.0 (from gmusicproxy==2.2.0->-r requirements.txt (line
 3))                                                                            
  Using cached https://files.pythonhosted.org/packages/ea/4d/0bc70c6684cff13b47f
27b7d6085bac8856fba382dca5c170b3d7651702c/gmusicapi-13.0.0.tar.gz               
Requirement already satisfied: netifaces>=0.10.4 in /usr/lib64/python2.7/site-pa
ckages (from gmusicproxy==2.2.0->-r requirements.txt (line 3))                  
Requirement already satisfied: pyxdg>=0.25 in /usr/lib/python2.7/site-packages (
from gmusicproxy==2.2.0->-r requirements.txt (line 3))                          
Collecting eyed3>=0.9.5 (from gmusicproxy==2.2.0->-r requirements.txt (line 3)) 
  Using cached https://files.pythonhosted.org/packages/bd/67/202bcc28b01684f8fe1
8921f4b1dbe44b471b2c407f5d784849d513e417f/eyeD3-0.9.5-py2.py3-none-any.whl      
Collecting python-daemon>=2.2.4 (from gmusicproxy==2.2.0->-r requirements.txt (l
ine 3))                                                                         
  Using cached https://files.pythonhosted.org/packages/5a/0c/57f15b1572661877ff1
acbe66c2f5be9d999ae5fb128e22933d374f62aa1/python_daemon-2.2.4-py2.py3-none-any.w
hl
Collecting Markdown>=3.2.1 (from gmusicproxy==2.2.0->-r requirements.txt (line 3
))
  Could not find a version that satisfies the requirement Markdown>=3.2.1 (from 
gmusicproxy==2.2.0->-r requirements.txt (line 3)) (from versions: 1.7, 2.0, 2.0.
1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.3, 2.3.1, 2.4, 2.4.1, 2.5, 2.5.1,
 2.5.2, 2.6, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.6.7, 2.6.8, 2.6.9, 2.6.
10, 2.6.11, 3.0, 3.0.1, 3.1, 3.1.1)
No matching distribution found for Markdown>=3.2.1 (from gmusicproxy==2.2.0->-r 
requirements.txt (line 3))
```

So I tried using [this stackoverflow issue] to ignore them, and try starting it. I ran `python GMusicProxy --config gmusicproxy.cfg`, but got this error:

```
Traceback (most recent call last):                                              
  File "/usr/bin/GMusicProxy", line 4, in <module>                              
    __import__('pkg_resources').require('gmusicproxy==1.0.9b2')                 
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3095, 
in <module>                                                                     
    @_call_aside                                                                
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3079, 
in _call_aside                                                                  
    f(*args, **kwargs)                                                          
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3108, 
in _initialize_master_working_set                                               
    working_set = WorkingSet._build_master()                                    
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, i
n _build_master                                                                 
    return cls._build_from_requirements(__requires__)                           
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 585, i
n _build_from_requirements                                                      
    dists = ws.resolve(reqs, Environment())                                     
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, i
n resolve                                                                       
    raise DistributionNotFound(req, requirers)                                  
pkg_resources.DistributionNotFound: The 'gmusicproxy==1.0.9b2' distribution was 
not found and is required by the application
```

**Comment by jdwoody** [comment]
Looks like you’re trying to run with python 2.7, which is no longer
supported. Please try again with a Python 3.8 runtime and let us know if
you have any issues.
