### ISSUE TITLE
Error after upgrade of python2-eyed3

### ISSUE THREAD

**Issue by freijon** [gmusicproxy/gmusicproxy#98]
On my Arch Linux installation there was an upgrade of python2-eyed3 to version 0.8.1. After this upgrade I get an error if I try to start GmusicProxy:
```
Traceback (most recent call last):
  File "/usr/bin/GMusicProxy", line 51, in <module>
    import eyed3.id3
  File "/usr/lib/python2.7/site-packages/eyed3/__init__.py", line 35, in <module>
    from .utils.log import log                                            # noqa
  File "/usr/lib/python2.7/site-packages/eyed3/utils/__init__.py", line 49, in <module>
    _mime_types = MagicTypes()
  File "/usr/lib/python2.7/site-packages/eyed3/utils/__init__.py", line 41, in __init__
    keep_going=False)
TypeError: __init__() got an unexpected keyword argument 'keep_going'
```

Also I had to install the python2-magic package which was not needed before that upgrade. GmusicProxy ran perfectly fine without that package.

**Comment by jdwoody** [comment]
@freijon If you're still using GMP, please try again with version 2.1.0 and open a new ticket. Python 2 support has been removed and dependencies updated
